// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwF70SDA7PwAnkFGC0YLTGopQs0YIIU_E',
    appId: '1:28051780042:web:25475ee012ea61c8275f33',
    messagingSenderId: '28051780042',
    projectId: 'firestore-support',
    authDomain: 'firestore-support.firebaseapp.com',
    storageBucket: 'firestore-support.firebasestorage.app',
    measurementId: 'G-20Y1K90TD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxlnJslz0aRjjoXrdiBxEHN4xu6JYbG5A',
    appId: '1:28051780042:android:bb84b1b4a6d4f4aa275f33',
    messagingSenderId: '28051780042',
    projectId: 'firestore-support',
    storageBucket: 'firestore-support.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBohUXaJ7QnYL2mO-Y8Vz6w94iDY-5d21Q',
    appId: '1:28051780042:ios:f5210efc74ea74bb275f33',
    messagingSenderId: '28051780042',
    projectId: 'firestore-support',
    storageBucket: 'firestore-support.firebasestorage.app',
    iosBundleId: 'com.example.firestoreSupport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBohUXaJ7QnYL2mO-Y8Vz6w94iDY-5d21Q',
    appId: '1:28051780042:ios:f5210efc74ea74bb275f33',
    messagingSenderId: '28051780042',
    projectId: 'firestore-support',
    storageBucket: 'firestore-support.firebasestorage.app',
    iosBundleId: 'com.example.firestoreSupport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwF70SDA7PwAnkFGC0YLTGopQs0YIIU_E',
    appId: '1:28051780042:web:ff24547ebdec8e71275f33',
    messagingSenderId: '28051780042',
    projectId: 'firestore-support',
    authDomain: 'firestore-support.firebaseapp.com',
    storageBucket: 'firestore-support.firebasestorage.app',
    measurementId: 'G-CG9BZ7JWTD',
  );
}
